import { API_CONSTANTS, KAKAO_CONSTANTS } from '../constants';

// API 설정
export const API_CONFIG = {
    // 백엔드 API URL
    BACKEND_URL: API_CONSTANTS.BACKEND_URL,
};

// 카카오 API 설정
export const KAKAO_API_CONFIG = {
    BASE_URL: KAKAO_CONSTANTS.BASE_URL,
    JAVASCRIPT_KEY: KAKAO_CONSTANTS.JAVASCRIPT_KEY,
    RESTAPI_KEY: KAKAO_CONSTANTS.RESTAPI_KEY,
    CLIENT_SECRET: KAKAO_CONSTANTS.CLIENT_SECRET,
};
