import asyncio
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from app.db.database import async_engine, Base, AsyncSessionLocal
from app.models import (
    User,
    Menu,
    Category,
    Question,
    UserAnswer,
    Recommendation,
    Favorite,
    UserPreference,
    UserInteraction,
)
from app.models.menu import TimeSlot
from app.models.question import Question
from app.models.user_answer import UserAnswer
from app.models.recommendation import Recommendation
from app.models.category import Category
import uuid
import json


async def init_db():
    """
    데이터베이스 전체 초기화 (테이블 삭제 후 재생성)
    - 운영 환경에서는 사용 금지 (개발/테스트용)
    """
    async with async_engine.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)
        await conn.run_sync(Base.metadata.create_all)
    await create_sample_data()


async def create_sample_data():
    """
    샘플 데이터(카테고리, 메뉴, 질문) 자동 생성
    - 카테고리 생성 후 id 매핑 → 메뉴에 category_id 할당
    - 실전 서비스 수준의 샘플 구조
    """
    from app.db.database import AsyncSessionLocal

    async with AsyncSessionLocal() as db:
        # 기존 데이터 확인 (중복 방지)
        result = await db.execute(select(Menu))
        existing_menus = result.scalars().all()
        if existing_menus:
            print("샘플 데이터가 이미 존재합니다.")
            return
        # 샘플 카테고리 데이터
        sample_categories = [
            {
                "name": "한국 전통 요리",
                "description": "한국의 전통적인 요리들",
                "country": "한국",
                "cuisine_type": "한식",
                "display_order": 1,
                "color_code": "#FF6B6B",
            },
            {
                "name": "중국 요리",
                "description": "다양한 중국 요리들",
                "country": "중국",
                "cuisine_type": "중식",
                "display_order": 2,
                "color_code": "#4ECDC4",
            },
            {
                "name": "일본 요리",
                "description": "정교한 일본 요리들",
                "country": "일본",
                "cuisine_type": "일식",
                "display_order": 3,
                "color_code": "#45B7D1",
            },
            {
                "name": "이탈리아 요리",
                "description": "풍부한 맛의 이탈리아 요리들",
                "country": "이탈리아",
                "cuisine_type": "양식",
                "display_order": 4,
                "color_code": "#96CEB4",
            },
            {
                "name": "태국 요리",
                "description": "매콤달콤한 태국 요리들",
                "country": "태국",
                "cuisine_type": "동남아식",
                "display_order": 5,
                "color_code": "#FFEAA7",
            },
            {
                "name": "인도 요리",
                "description": "향신료가 풍부한 인도 요리들",
                "country": "인도",
                "cuisine_type": "인도식",
                "display_order": 6,
                "color_code": "#DDA0DD",
            },
        ]
        # 카테고리 데이터 저장 및 이름→id 매핑
        category_name_to_id = {}
        for category_data in sample_categories:
            category = Category(**category_data)
            db.add(category)
        await db.commit()  # 카테고리 ID 확보를 위해 commit

        # 생성된 카테고리들의 ID를 다시 조회하여 매핑
        for category_data in sample_categories:
            result = await db.execute(
                select(Category).where(Category.name == category_data["name"])
            )
            category = result.scalar_one()
            category_name_to_id[category_data["name"]] = category.id
        # 샘플 메뉴 데이터 (카테고리 연관관계 반영)
        sample_menus = [
            # 한식(한국 전통 요리) - 10개 이상
            {
                "name": "김치볶음밥",
                "description": "매콤한 김치와 함께 볶은 맛있는 볶음밥",
                "time_slot": "breakfast",
                "is_spicy": True,
                "is_healthy": False,
                "is_vegetarian": False,
                "is_quick": True,
                "has_rice": True,
                "has_soup": False,
                "has_meat": False,
                "calories": 450,
                "protein": 10.0,
                "carbs": 70.0,
                "fat": 12.0,
                "prep_time": 15,
                "difficulty": "easy",
                "rating": 4.5,
                "image_url": "https://cdn.ozm.com/kimchi_fried_rice.jpg",
                "category_id": category_name_to_id["한국 전통 요리"],
            },
            {
                "name": "비빔밥",
                "description": "다양한 나물과 고추장을 비빈 한국 전통 요리",
                "time_slot": "lunch",
                "is_spicy": False,
                "is_healthy": True,
                "is_vegetarian": True,
                "is_quick": False,
                "has_rice": True,
                "has_soup": False,
                "has_meat": False,
                "calories": 500,
                "protein": 12.0,
                "carbs": 80.0,
                "fat": 10.0,
                "prep_time": 20,
                "difficulty": "medium",
                "rating": 4.7,
                "image_url": "https://cdn.ozm.com/bibimbap.jpg",
                "category_id": category_name_to_id["한국 전통 요리"],
            },
            {
                "name": "불고기",
                "description": "달콤하게 양념한 소고기 구이",
                "time_slot": "lunch",
                "is_spicy": False,
                "is_healthy": False,
                "is_vegetarian": False,
                "is_quick": False,
                "has_rice": False,
                "has_soup": False,
                "has_meat": True,
                "calories": 600,
                "protein": 28.0,
                "carbs": 15.0,
                "fat": 35.0,
                "prep_time": 30,
                "difficulty": "medium",
                "rating": 4.8,
                "image_url": "https://cdn.ozm.com/bulgogi.jpg",
                "category_id": category_name_to_id["한국 전통 요리"],
            },
            {
                "name": "된장찌개",
                "description": "구수한 된장의 맛이 일품인 국물 요리",
                "time_slot": "lunch",
                "is_spicy": False,
                "is_healthy": True,
                "is_vegetarian": True,
                "is_quick": False,
                "has_rice": False,
                "has_soup": True,
                "has_meat": False,
                "calories": 200,
                "protein": 8.0,
                "carbs": 15.0,
                "fat": 7.0,
                "prep_time": 25,
                "difficulty": "easy",
                "rating": 4.3,
                "image_url": "https://cdn.ozm.com/doenjang_stew.jpg",
                "category_id": category_name_to_id["한국 전통 요리"],
            },
            {
                "name": "삼겹살",
                "description": "구워서 먹는 대표적인 한국 고기 요리",
                "time_slot": "dinner",
                "is_spicy": False,
                "is_healthy": False,
                "is_vegetarian": False,
                "is_quick": False,
                "has_rice": False,
                "has_soup": False,
                "has_meat": True,
                "calories": 700,
                "protein": 25.0,
                "carbs": 5.0,
                "fat": 60.0,
                "prep_time": 20,
                "difficulty": "easy",
                "rating": 4.9,
                "image_url": "https://cdn.ozm.com/samgyeopsal.jpg",
                "category_id": category_name_to_id["한국 전통 요리"],
            },
            {
                "name": "김치찌개",
                "description": "매콤한 김치로 끓인 뜨끈한 찌개",
                "time_slot": "dinner",
                "is_spicy": True,
                "is_healthy": False,
                "is_vegetarian": False,
                "is_quick": False,
                "has_rice": False,
                "has_soup": True,
                "has_meat": False,
                "calories": 350,
                "protein": 10.0,
                "carbs": 12.0,
                "fat": 15.0,
                "prep_time": 30,
                "difficulty": "easy",
                "rating": 4.6,
                "image_url": "https://cdn.ozm.com/kimchi_stew.jpg",
                "category_id": category_name_to_id["한국 전통 요리"],
            },
            {
                "name": "잡채",
                "description": "당면과 다양한 야채, 고기를 볶아 만든 한국식 잡채",
                "time_slot": "dinner",
                "is_spicy": False,
                "is_healthy": True,
                "is_vegetarian": False,
                "is_quick": False,
                "has_rice": False,
                "has_soup": False,
                "has_meat": True,
                "calories": 400,
                "protein": 10.0,
                "carbs": 60.0,
                "fat": 10.0,
                "prep_time": 35,
                "difficulty": "medium",
                "rating": 4.4,
                "image_url": "https://cdn.ozm.com/japchae.jpg",
                "category_id": category_name_to_id["한국 전통 요리"],
            },
            {
                "name": "갈비탕",
                "description": "소갈비를 푹 고아 만든 맑은 국물 요리",
                "time_slot": "lunch",
                "is_spicy": False,
                "is_healthy": True,
                "is_vegetarian": False,
                "is_quick": False,
                "has_rice": False,
                "has_soup": True,
                "has_meat": True,
                "calories": 550,
                "protein": 30.0,
                "carbs": 8.0,
                "fat": 25.0,
                "prep_time": 60,
                "difficulty": "hard",
                "rating": 4.8,
                "image_url": "https://cdn.ozm.com/galbitang.jpg",
                "category_id": category_name_to_id["한국 전통 요리"],
            },
            {
                "name": "떡볶이",
                "description": "쫄깃한 떡과 매콤달콤한 소스의 국민 간식",
                "time_slot": "dinner",
                "is_spicy": True,
                "is_healthy": False,
                "is_vegetarian": True,
                "is_quick": True,
                "has_rice": False,
                "has_soup": False,
                "has_meat": False,
                "calories": 350,
                "protein": 6.0,
                "carbs": 75.0,
                "fat": 3.0,
                "prep_time": 20,
                "difficulty": "easy",
                "rating": 4.3,
                "image_url": "https://cdn.ozm.com/tteokbokki.jpg",
                "category_id": category_name_to_id["한국 전통 요리"],
            },
            {
                "name": "콩나물국밥",
                "description": "콩나물과 밥이 어우러진 시원한 국밥",
                "time_slot": "breakfast",
                "is_spicy": False,
                "is_healthy": True,
                "is_vegetarian": True,
                "is_quick": False,
                "has_rice": True,
                "has_soup": True,
                "has_meat": False,
                "calories": 300,
                "protein": 10.0,
                "carbs": 55.0,
                "fat": 4.0,
                "prep_time": 25,
                "difficulty": "easy",
                "rating": 4.1,
                "image_url": "https://cdn.ozm.com/kongnamul_gukbap.jpg",
                "category_id": category_name_to_id["한국 전통 요리"],
            },
            # 중식
            {
                "name": "짜장면",
                "description": "달콤짭짤한 춘장 소스의 대표 중화면 요리",
                "time_slot": "lunch",
                "is_spicy": False,
                "is_healthy": False,
                "is_vegetarian": False,
                "is_quick": True,
                "has_rice": False,
                "has_soup": False,
                "has_meat": True,
                "calories": 650,
                "protein": 15.0,
                "carbs": 90.0,
                "fat": 18.0,
                "prep_time": 20,
                "difficulty": "easy",
                "rating": 4.2,
                "image_url": "https://cdn.ozm.com/jjajangmyeon.jpg",
                "category_id": category_name_to_id["중국 요리"],
            },
            {
                "name": "마파두부",
                "description": "매콤한 두반장 소스와 두부의 조화",
                "time_slot": "dinner",
                "is_spicy": True,
                "is_healthy": True,
                "is_vegetarian": False,
                "is_quick": False,
                "has_rice": False,
                "has_soup": False,
                "has_meat": True,
                "calories": 400,
                "protein": 18.0,
                "carbs": 12.0,
                "fat": 28.0,
                "prep_time": 25,
                "difficulty": "medium",
                "rating": 4.4,
                "image_url": "https://cdn.ozm.com/mapo_tofu.jpg",
                "category_id": category_name_to_id["중국 요리"],
            },
            # 일식
            {
                "name": "초밥",
                "description": "신선한 생선과 밥의 조화, 일본 대표 요리",
                "time_slot": "lunch",
                "is_spicy": False,
                "is_healthy": True,
                "is_vegetarian": False,
                "is_quick": False,
                "has_rice": True,
                "has_soup": False,
                "has_meat": True,
                "calories": 350,
                "protein": 20.0,
                "carbs": 60.0,
                "fat": 5.0,
                "prep_time": 30,
                "difficulty": "hard",
                "rating": 4.7,
                "image_url": "https://cdn.ozm.com/sushi.jpg",
                "category_id": category_name_to_id["일본 요리"],
            },
            {
                "name": "우동",
                "description": "쫄깃한 면발과 따뜻한 국물의 일본식 우동",
                "time_slot": "dinner",
                "is_spicy": False,
                "is_healthy": True,
                "is_vegetarian": True,
                "is_quick": False,
                "has_rice": False,
                "has_soup": True,
                "has_meat": False,
                "calories": 320,
                "protein": 8.0,
                "carbs": 65.0,
                "fat": 2.0,
                "prep_time": 20,
                "difficulty": "easy",
                "rating": 4.1,
                "image_url": "https://cdn.ozm.com/udon.jpg",
                "category_id": category_name_to_id["일본 요리"],
            },
            # 양식(이탈리아)
            {
                "name": "마르게리타 피자",
                "description": "토마토와 모짜렐라, 바질의 클래식한 조화",
                "time_slot": "dinner",
                "is_spicy": False,
                "is_healthy": False,
                "is_vegetarian": True,
                "is_quick": False,
                "has_rice": False,
                "has_soup": False,
                "has_meat": False,
                "calories": 800,
                "protein": 22.0,
                "carbs": 90.0,
                "fat": 35.0,
                "prep_time": 30,
                "difficulty": "medium",
                "rating": 4.6,
                "image_url": "https://cdn.ozm.com/margherita_pizza.jpg",
                "category_id": category_name_to_id["이탈리아 요리"],
            },
            {
                "name": "까르보나라",
                "description": "크리미한 소스와 베이컨의 풍미가 어우러진 파스타",
                "time_slot": "lunch",
                "is_spicy": False,
                "is_healthy": False,
                "is_vegetarian": False,
                "is_quick": False,
                "has_rice": False,
                "has_soup": False,
                "has_meat": True,
                "calories": 700,
                "protein": 20.0,
                "carbs": 80.0,
                "fat": 30.0,
                "prep_time": 25,
                "difficulty": "medium",
                "rating": 4.5,
                "image_url": "https://cdn.ozm.com/carbonara.jpg",
                "category_id": category_name_to_id["이탈리아 요리"],
            },
            # 동남아
            {
                "name": "팟타이",
                "description": "쫄깃한 쌀국수와 새콤달콤한 소스의 태국식 볶음면",
                "time_slot": "dinner",
                "is_spicy": False,
                "is_healthy": True,
                "is_vegetarian": False,
                "is_quick": True,
                "has_rice": False,
                "has_soup": False,
                "has_meat": True,
                "calories": 550,
                "protein": 15.0,
                "carbs": 80.0,
                "fat": 12.0,
                "prep_time": 20,
                "difficulty": "medium",
                "rating": 4.4,
                "image_url": "https://cdn.ozm.com/pad_thai.jpg",
                "category_id": category_name_to_id["태국 요리"],
            },
            {
                "name": "똠얌꿍",
                "description": "매콤새콤한 태국식 해산물 수프",
                "time_slot": "lunch",
                "is_spicy": True,
                "is_healthy": True,
                "is_vegetarian": False,
                "is_quick": False,
                "has_rice": False,
                "has_soup": True,
                "has_meat": False,
                "calories": 180,
                "protein": 8.0,
                "carbs": 10.0,
                "fat": 6.0,
                "prep_time": 25,
                "difficulty": "medium",
                "rating": 4.2,
                "image_url": "https://cdn.ozm.com/tom_yum_goong.jpg",
                "category_id": category_name_to_id["태국 요리"],
            },
            # 인도
            {
                "name": "치킨 티카 마살라",
                "description": "향신료와 토마토 소스가 어우러진 인도식 치킨 커리",
                "time_slot": "dinner",
                "is_spicy": True,
                "is_healthy": False,
                "is_vegetarian": False,
                "is_quick": False,
                "has_rice": False,
                "has_soup": False,
                "has_meat": True,
                "calories": 600,
                "protein": 30.0,
                "carbs": 20.0,
                "fat": 35.0,
                "prep_time": 40,
                "difficulty": "hard",
                "rating": 4.7,
                "image_url": "https://cdn.ozm.com/chicken_tikka_masala.jpg",
                "category_id": category_name_to_id["인도 요리"],
            },
            {
                "name": "팔락 파니르",
                "description": "시금치와 인도 치즈가 어우러진 채식 커리",
                "time_slot": "lunch",
                "is_spicy": False,
                "is_healthy": True,
                "is_vegetarian": True,
                "is_quick": False,
                "has_rice": False,
                "has_soup": False,
                "has_meat": False,
                "calories": 350,
                "protein": 12.0,
                "carbs": 18.0,
                "fat": 20.0,
                "prep_time": 30,
                "difficulty": "medium",
                "rating": 4.3,
                "image_url": "https://cdn.ozm.com/palak_paneer.jpg",
                "category_id": category_name_to_id["인도 요리"],
            },
        ]
        for menu_data in sample_menus:
            menu = Menu(**menu_data)
            db.add(menu)
        # 샘플 질문 데이터
        sample_questions = [
            {
                "text": "매운 음식을 좋아하시나요?",
                "question_type": "preference",
                "options": json.dumps(["매운맛", "순한맛"]),
                "display_order": 1,
            },
            {
                "text": "어떤 식단을 선호하시나요?",
                "question_type": "preference",
                "options": json.dumps(["건강식", "일반식", "채식"]),
                "display_order": 2,
            },
            {
                "text": "조리 시간은 어느 정도를 원하시나요?",
                "question_type": "preference",
                "options": json.dumps(["빠른조리", "일반조리"]),
                "display_order": 3,
            },
            {
                "text": "어떤 종류의 음식을 좋아하시나요?",
                "question_type": "preference",
                "options": json.dumps(["밥류", "국물요리", "고기요리"]),
                "display_order": 4,
            },
            {
                "text": "식사 시간대는 언제인가요?",
                "question_type": "filter",
                "options": json.dumps(["아침", "점심", "저녁"]),
                "display_order": 5,
            },
            {
                "text": "선호하는 난이도는?",
                "question_type": "preference",
                "options": json.dumps(["쉬움", "보통", "어려움"]),
                "display_order": 6,
            },
        ]
        for question_data in sample_questions:
            question = Question(**question_data)
            db.add(question)
        await db.commit()
        print("샘플 데이터가 성공적으로 생성되었습니다.")


if __name__ == "__main__":
    asyncio.run(init_db())
