import { StyleSheet } from 'react-native';
import { colors, typography, spacing, shadows } from './GlobalStyles';

export const LoginScreenStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background,
        justifyContent: 'center',
        alignItems: 'center',
        padding: spacing.lg,
    },
    form: {
        width: '100%',
        maxWidth: 400,
        alignItems: 'center',
    },
    header: {
        alignItems: 'center',
        marginBottom: spacing.xl,
    },
    logo: {
        fontSize: 48,
        fontWeight: '700' as const,
        color: colors.primary,
        marginBottom: spacing.sm,
    },
    title: {
        ...typography.h2,
        color: colors.text.primary,
        textAlign: 'center',
        marginBottom: spacing.sm,
    },
    subtitle: {
        ...typography.body1,
        color: colors.text.secondary,
        textAlign: 'center',
        lineHeight: 24,
    },
    kakaoLoginButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#FEE500',
        paddingVertical: spacing.md,
        paddingHorizontal: spacing.xl,
        borderRadius: 16,
        width: '100%',
        ...shadows.medium,
        borderWidth: 1,
        borderColor: '#E6D800',
    },
    kakaoLoginButtonDisabled: {
        backgroundColor: colors.border.medium,
        shadowOpacity: 0,
        elevation: 0,
    },
    kakaoLoginButtonText: {
        ...typography.button,
        color: '#3C1E1E',
        fontWeight: '600' as const,
    },
    loginSuccessBadge: {
        position: 'absolute',
        top: 50,
        right: 20,
        backgroundColor: colors.status.success,
        paddingHorizontal: spacing.sm,
        paddingVertical: spacing.xs,
        borderRadius: 16,
        zIndex: 1000,
        ...shadows.small,
    },
    loginSuccessBadgeText: {
        color: colors.text.inverse,
        fontSize: 12,
        fontWeight: '600' as const,
    },
    userInfoContainer: {
        width: '100%',
        alignItems: 'center',
    },
    userProfileCard: {
        backgroundColor: colors.surface,
        borderRadius: 20,
        padding: spacing.xl,
        width: '100%',
        alignItems: 'center',
        marginBottom: spacing.lg,
        ...shadows.medium,
        borderWidth: 1,
        borderColor: colors.border.light,
    },
    userAvatar: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: colors.surfaceSecondary,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: spacing.md,
        ...shadows.small,
    },
    userName: {
        ...typography.h3,
        color: colors.text.primary,
        marginBottom: spacing.xs,
        textAlign: 'center',
    },
    userEmail: {
        ...typography.body1,
        color: colors.text.secondary,
        marginBottom: spacing.md,
        textAlign: 'center',
    },
    loginStatusContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.status.success + '10',
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.sm,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.status.success + '20',
    },
    loginStatusText: {
        marginLeft: spacing.xs,
        ...typography.body2,
        color: colors.status.success,
        fontWeight: '500' as const,
    },
    logoutButton: {
        backgroundColor: colors.status.error,
        paddingVertical: spacing.md,
        paddingHorizontal: spacing.xl,
        borderRadius: 16,
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        ...shadows.medium,
    },
    logoutButtonText: {
        ...typography.button,
        color: colors.text.inverse,
        fontWeight: '600' as const,
    },
    loadingContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    loadingText: {
        marginLeft: spacing.sm,
        ...typography.body1,
        color: colors.text.secondary,
    },
    errorContainer: {
        backgroundColor: colors.status.error + '10',
        padding: spacing.md,
        borderRadius: 12,
        marginTop: spacing.md,
        borderWidth: 1,
        borderColor: colors.status.error + '20',
        width: '100%',
    },
    errorText: {
        ...typography.body2,
        color: colors.status.error,
        textAlign: 'center',
        fontWeight: '500' as const,
    },
    welcomeContainer: {
        alignItems: 'center',
        marginBottom: spacing.xl,
    },
    welcomeIcon: {
        marginBottom: spacing.lg,
        opacity: 0.8,
    },
    welcomeText: {
        ...typography.h2,
        color: colors.text.primary,
        textAlign: 'center',
        marginBottom: spacing.sm,
    },
    welcomeSubtext: {
        ...typography.body1,
        color: colors.text.secondary,
        textAlign: 'center',
        lineHeight: 24,
    },
});
