import { StyleSheet } from 'react-native';

export const MenuRecommendationStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F2F2F7',
    },
    header: {
        padding: 20,
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#E5E5EA',
    },
    title: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#1C1C1E',
        marginBottom: 8,
    },
    subtitle: {
        fontSize: 16,
        color: '#8E8E93',
    },
    inputContainer: {
        padding: 20,
        backgroundColor: '#fff',
        marginBottom: 10,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#1C1C1E',
        marginBottom: 15,
    },
    timeSlotContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 20,
    },
    timeSlotButton: {
        flex: 1,
        alignItems: 'center',
        padding: 15,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#E5E5EA',
        marginHorizontal: 5,
    },
    timeSlotButtonActive: {
        backgroundColor: '#007AFF',
        borderColor: '#007AFF',
    },
    timeSlotText: {
        marginTop: 5,
        fontSize: 14,
        fontWeight: '500',
        color: '#007AFF',
    },
    timeSlotTextActive: {
        color: '#fff',
    },
    button: {
        backgroundColor: '#007AFF',
        padding: 15,
        borderRadius: 12,
        alignItems: 'center',
    },
    buttonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    loadingContainer: {
        padding: 40,
        alignItems: 'center',
    },
    loadingText: {
        marginTop: 10,
        fontSize: 16,
        color: '#8E8E93',
    },
    errorContainer: {
        padding: 20,
        backgroundColor: '#FFE5E5',
        margin: 20,
        borderRadius: 12,
    },
    errorText: {
        color: '#FF3B30',
        textAlign: 'center',
    },
    recommendationsContainer: {
        padding: 20,
    },
    recommendationsTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#1C1C1E',
        marginBottom: 15,
    },
    menuCard: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 15,
        marginBottom: 10,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 3.84,
        elevation: 5,
    },
    menuHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    menuName: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#1C1C1E',
        flex: 1,
    },
    ratingContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    ratingText: {
        marginLeft: 5,
        fontSize: 14,
        color: '#8E8E93',
    },
    menuDescription: {
        fontSize: 14,
        color: '#3A3A3C',
        lineHeight: 20,
        marginBottom: 10,
    },
    cardFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 10,
    },
    categoryContainer: {
        alignSelf: 'flex-start',
    },
    categoryText: {
        backgroundColor: '#E5E5EA',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 6,
        fontSize: 12,
        color: '#8E8E93',
    },
    reasonContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
        backgroundColor: '#E7F3FF',
        padding: 8,
        borderRadius: 8,
    },
    reasonText: {
        marginLeft: 8,
        fontSize: 13,
        color: '#00529B',
        flex: 1,
    },
    addButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#E7F3FF',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 20,
    },
    addButtonText: {
        marginLeft: 6,
        fontSize: 14,
        fontWeight: '600',
        color: '#007AFF',
    },
    removeButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFE7E7',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 20,
    },
    removeButtonText: {
        marginLeft: 6,
        fontSize: 14,
        fontWeight: '600',
        color: '#FF3B30',
    },
    // A/B 테스트 정보 스타일
    abTestContainer: {
        backgroundColor: '#F0F8FF',
        borderRadius: 8,
        padding: 10,
        marginBottom: 10,
        borderLeftWidth: 3,
        borderLeftColor: '#007AFF',
    },
    abTestHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 6,
    },
    abTestTitle: {
        marginLeft: 6,
        fontSize: 12,
        fontWeight: '600',
        color: '#007AFF',
    },
    weightSetContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
    },
    weightText: {
        fontSize: 11,
        color: '#666',
        marginRight: 8,
        marginBottom: 2,
    },
    // 협업 필터링 스타일
    collaborativeContainer: {
        backgroundColor: '#FFF8E1',
        borderRadius: 8,
        padding: 10,
        marginBottom: 10,
        borderLeftWidth: 3,
        borderLeftColor: '#FFA000',
    },
    collaborativeHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 6,
    },
    collaborativeTitle: {
        marginLeft: 6,
        fontSize: 12,
        fontWeight: '600',
        color: '#FFA000',
    },
    similarityInfo: {
        flexDirection: 'row',
        flexWrap: 'wrap',
    },
    similarityText: {
        fontSize: 11,
        color: '#666',
        marginRight: 8,
        marginBottom: 2,
    },
    modeSwitchContainer: {
        flexDirection: 'row',
        marginBottom: 16,
    },
    modeButton: {
        flex: 1,
        padding: 12,
        borderRadius: 8,
        backgroundColor: '#E5E5EA',
        marginHorizontal: 4,
        alignItems: 'center',
    },
    modeButtonActive: {
        backgroundColor: '#007AFF',
    },
    modeButtonText: {
        color: '#1C1C1E',
        textAlign: 'center',
        fontWeight: 'bold',
    },
    categoryModalButton: {
        backgroundColor: '#E5E5EA',
        borderRadius: 8,
        padding: 12,
        marginBottom: 10,
        alignItems: 'center',
    },
    categoryModalOverlay: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.3)',
    },
    categoryModalContent: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 20,
        width: '85%',
        maxHeight: '70%',
        elevation: 8,
        shadowColor: 'transparent',
    },
    categoryModalTitle: {
        fontWeight: 'bold',
        fontSize: 18,
        marginBottom: 16,
        textAlign: 'center',
    },
    categoryModalItem: {
        paddingVertical: 14,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
    },
    categoryModalItemText: {
        color: '#1C1C1E',
        fontWeight: 'normal',
        fontSize: 16,
        textAlign: 'center',
    },
    categoryModalItemTextActive: {
        color: '#007AFF',
        fontWeight: 'bold',
    },
    categoryModalCloseButton: {
        marginTop: 16,
        alignItems: 'center',
        padding: 12,
        borderRadius: 8,
        backgroundColor: '#E5E5EA',
    },
    categoryModalCloseButtonText: {
        color: '#1C1C1E',
        fontWeight: 'bold',
    },
    quizOptionButton: {
        backgroundColor: '#E5E5EA',
        borderRadius: 20,
        paddingHorizontal: 16,
        paddingVertical: 8,
        marginRight: 8,
        marginBottom: 8,
    },
    quizOptionButtonActive: {
        backgroundColor: '#007AFF',
    },
    quizOptionText: {
        color: '#1C1C1E',
        fontWeight: '500',
    },
    quizOptionTextActive: {
        color: '#fff',
    },
});
