import { StyleSheet, Platform, Dimensions } from 'react-native';
import { colors, typography, spacing, shadows } from './GlobalStyles';

const { width, height } = Dimensions.get('window');

export const NearbyStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: spacing.xl,
    },
    loadingText: {
        marginTop: spacing.md,
        ...typography.body1,
        color: colors.text.secondary,
    },
    errorContainer: {
        padding: spacing.lg,
        backgroundColor: colors.status.error + '10',
        margin: spacing.lg,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: colors.status.error + '20',
    },
    errorTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#1C1C1E',
        marginTop: 20,
        marginBottom: 10,
    },
    errorText: {
        color: colors.status.error,
        textAlign: 'center',
        ...typography.body1,
        fontWeight: '500' as const,
    },
    retryButton: {
        backgroundColor: '#007AFF',
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderRadius: 8,
    },
    retryButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: spacing.lg,
        backgroundColor: colors.surface,
        borderBottomWidth: 1,
        borderBottomColor: colors.border.light,
        ...shadows.small,
    },
    locationInfo: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        marginRight: spacing.md,
    },
    locationText: {
        flex: 1,
        marginLeft: spacing.sm,
    },
    locationTitle: {
        ...typography.body2,
        color: colors.text.secondary,
        fontWeight: '600' as const,
        marginBottom: spacing.xs,
    },
    locationAddress: {
        ...typography.body1,
        color: colors.text.primary,
        fontWeight: '500' as const,
        lineHeight: 20,
    },
    locationHint: {
        ...typography.caption,
        color: colors.primary,
        marginTop: spacing.xs,
    },
    refreshButton: {
        padding: spacing.sm,
        borderRadius: 20,
        backgroundColor: colors.surfaceSecondary,
        ...shadows.small,
    },
    content: {
        padding: spacing.lg,
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: spacing.md,
        backgroundColor: colors.surface,
        borderRadius: 16,
        paddingHorizontal: spacing.md,
        ...shadows.small,
        borderWidth: 1,
        borderColor: colors.border.light,
    },
    searchInput: {
        flex: 1,
        paddingVertical: spacing.md,
        ...typography.body1,
        color: colors.text.primary,
    },
    searchButton: {
        padding: spacing.sm,
        borderRadius: 12,
        backgroundColor: colors.primary,
        ...shadows.small,
    },
    radiusContainer: {
        marginBottom: spacing.lg,
    },
    radiusLabel: {
        ...typography.body2,
        color: colors.text.secondary,
        marginBottom: spacing.sm,
        fontWeight: '500' as const,
    },
    radiusButtons: {
        flexDirection: 'row',
        gap: spacing.sm,
    },
    radiusButton: {
        flex: 1,
        paddingVertical: spacing.sm,
        paddingHorizontal: spacing.md,
        borderRadius: 12,
        backgroundColor: colors.surfaceSecondary,
        borderWidth: 1,
        borderColor: colors.border.light,
        alignItems: 'center',
        justifyContent: 'center',
    },
    radiusButtonActive: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    radiusButtonText: {
        ...typography.body2,
        color: colors.text.secondary,
        fontWeight: '500' as const,
    },
    radiusButtonTextActive: {
        color: colors.text.inverse,
    },
    sortContainer: {
        marginBottom: 20,
    },
    sortLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1C1C1E',
        marginBottom: 12,
    },
    sortButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 8,
    },
    sortButton: {
        flex: 1,
        backgroundColor: '#fff',
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 8,
        marginHorizontal: 4,
        borderWidth: 1,
        borderColor: '#E5E5EA',
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
    },
    sortButtonActive: {
        backgroundColor: '#007AFF',
        borderColor: '#007AFF',
    },
    sortButtonText: {
        fontSize: 14,
        color: '#8E8E93',
        fontWeight: '500',
        marginLeft: 4,
    },
    sortButtonTextActive: {
        color: '#fff',
    },
    sectionTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#1C1C1E',
        marginBottom: 20,
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: spacing.xl,
        minHeight: height * 0.4,
    },
    emptyText: {
        ...typography.h3,
        color: colors.text.primary,
        textAlign: 'center',
        marginBottom: spacing.sm,
    },
    emptySubtext: {
        ...typography.body1,
        color: colors.text.secondary,
        textAlign: 'center',
        lineHeight: 24,
    },
    restaurantCard: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 3.84,
        elevation: 5,
    },
    restaurantContent: {
        flex: 1,
    },
    restaurantHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: spacing.sm,
    },
    restaurantName: {
        ...typography.h3,
        color: colors.text.primary,
        flex: 1,
        marginRight: spacing.sm,
    },
    ratingContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    ratingText: {
        marginLeft: spacing.xs,
        ...typography.body2,
        color: colors.text.secondary,
        fontWeight: '600' as const,
    },
    restaurantInfo: {
        marginBottom: spacing.md,
    },
    categoryContainer: {
        backgroundColor: '#E5E5EA',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 6,
    },
    categoryText: {
        fontSize: 12,
        color: '#8E8E93',
        fontWeight: '500',
    },
    distanceContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    distanceText: {
        marginLeft: 4,
        fontSize: 14,
        color: '#8E8E93',
    },
    addressText: {
        fontSize: 14,
        color: '#3A3A3C',
        lineHeight: 20,
        marginBottom: 12,
    },
    cardFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    phoneButton: {
        backgroundColor: colors.status.success + '10',
        borderColor: colors.status.success + '20',
    },
    phoneButtonText: {
        color: colors.status.success,
    },
    mapButton: {
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: spacing.sm,
        padding: 0,
        minWidth: undefined,
        minHeight: undefined,
        backgroundColor: 'transparent',
        borderWidth: 0,
    },
    mapButtonText: {
        color: colors.text.inverse,
    },
    mapThumbnailContainer: {
        marginTop: 10,
        marginBottom: 10,
        borderRadius: 12,
        overflow: 'hidden',
        position: 'relative',
        alignItems: 'center',
    },
    mapThumbnail: {
        width: '100%',
        height: 120,
        borderRadius: 12,
        backgroundColor: '#F2F2F7',
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'column',
    },
    mapThumbnailText: {
        color: '#007AFF',
        fontSize: 16,
        fontWeight: '600',
        marginTop: 8,
    },
    // 모달 스타일
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 20,
        margin: 20,
        width: '90%',
        maxWidth: 400,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#1C1C1E',
    },
    sortOptions: {
        gap: 12,
    },
    sortOption: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#E5E5EA',
        backgroundColor: '#fff',
    },
    sortOptionActive: {
        backgroundColor: '#007AFF',
        borderColor: '#007AFF',
    },
    sortOptionText: {
        fontSize: 16,
        color: '#1C1C1E',
        fontWeight: '500',
        marginLeft: 12,
    },
    sortOptionTextActive: {
        color: '#fff',
    },
    // 무한 스크롤을 위한 새로운 스타일들
    listContainer: {
        flex: 1,
    },
    listContentContainer: {
        paddingBottom: 20,
    },
    loadMoreContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        padding: spacing.lg,
    },
    loadMoreText: {
        marginLeft: spacing.sm,
        ...typography.body1,
        color: colors.text.secondary,
    },
    filterContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: spacing.lg,
        gap: spacing.sm,
    },
    filterButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: spacing.sm,
        paddingHorizontal: spacing.md,
        borderRadius: 20,
        backgroundColor: colors.surfaceSecondary,
        borderWidth: 1,
        borderColor: colors.border.light,
    },
    filterButtonActive: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    filterButtonText: {
        ...typography.body2,
        color: colors.text.secondary,
        fontWeight: '500' as const,
        marginLeft: spacing.xs,
    },
    filterButtonTextActive: {
        color: colors.text.inverse,
    },
    restaurantList: {
        flex: 1,
    },
    restaurantItem: {
        backgroundColor: colors.surface,
        borderRadius: 16,
        padding: spacing.lg,
        marginBottom: spacing.md,
        ...shadows.medium,
        borderWidth: 1,
        borderColor: colors.border.light,
    },
    restaurantCategory: {
        backgroundColor: colors.primary + '10',
        paddingHorizontal: spacing.sm,
        paddingVertical: spacing.xs,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: colors.primary + '20',
    },
    restaurantCategoryText: {
        ...typography.caption,
        color: colors.primary,
        fontWeight: '600' as const,
    },
    restaurantAddress: {
        ...typography.body2,
        color: colors.text.secondary,
        marginBottom: spacing.xs,
        lineHeight: 20,
    },
    restaurantDistance: {
        ...typography.body2,
        color: colors.text.tertiary,
        fontWeight: '500' as const,
    },
    restaurantRating: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: spacing.sm,
    },
    restaurantActions: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: spacing.sm,
    },
    actionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: spacing.sm,
        paddingHorizontal: spacing.md,
        borderRadius: 12,
        backgroundColor: colors.surfaceSecondary,
        borderWidth: 1,
        borderColor: colors.border.light,
    },
    actionButtonText: {
        marginLeft: spacing.xs,
        ...typography.body2,
        color: colors.text.secondary,
        fontWeight: '500' as const,
    },
    mapModal: {
        flex: 1,
        backgroundColor: colors.surface,
    },
    mapHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: spacing.lg,
        backgroundColor: colors.surface,
        borderBottomWidth: 1,
        borderBottomColor: colors.border.light,
        ...shadows.small,
    },
    mapTitle: {
        ...typography.h3,
        color: colors.text.primary,
        flex: 1,
        marginRight: spacing.md,
    },
    mapCloseButton: {
        padding: spacing.sm,
        borderRadius: 20,
        backgroundColor: colors.surfaceSecondary,
        ...shadows.small,
    },
    ratingModal: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    ratingModalContent: {
        backgroundColor: colors.surface,
        borderRadius: 20,
        padding: spacing.xl,
        margin: spacing.lg,
        maxWidth: width * 0.9,
        ...shadows.large,
    },
    ratingModalTitle: {
        ...typography.h3,
        color: colors.text.primary,
        textAlign: 'center',
        marginBottom: spacing.lg,
    },
    ratingButtons: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginBottom: spacing.lg,
    },
    ratingButton: {
        padding: spacing.sm,
        borderRadius: 12,
        backgroundColor: colors.surfaceSecondary,
        borderWidth: 1,
        borderColor: colors.border.light,
    },
    ratingButtonActive: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    ratingButtonText: {
        ...typography.body2,
        color: colors.text.secondary,
        fontWeight: '500' as const,
    },
    ratingButtonTextActive: {
        color: colors.text.inverse,
    },
    ratingModalActions: {
        flexDirection: 'row',
        gap: spacing.md,
    },
    ratingModalButton: {
        flex: 1,
        paddingVertical: spacing.md,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
    },
    ratingModalButtonCancel: {
        backgroundColor: colors.surfaceSecondary,
        borderWidth: 1,
        borderColor: colors.border.light,
    },
    ratingModalButtonConfirm: {
        backgroundColor: colors.primary,
        ...shadows.medium,
    },
    ratingModalButtonText: {
        ...typography.button,
        fontWeight: '600' as const,
    },
    ratingModalButtonTextCancel: {
        color: colors.text.secondary,
    },
    ratingModalButtonTextConfirm: {
        color: colors.text.inverse,
    },
    permissionContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: spacing.xl,
    },
    permissionText: {
        ...typography.body1,
        color: colors.text.secondary,
        textAlign: 'center',
        marginBottom: spacing.lg,
        lineHeight: 24,
    },
    permissionButton: {
        backgroundColor: colors.primary,
        paddingVertical: spacing.md,
        paddingHorizontal: spacing.xl,
        borderRadius: 16,
        ...shadows.medium,
    },
    permissionButtonText: {
        ...typography.button,
        color: colors.text.inverse,
        fontWeight: '600' as const,
    },
});
