import { StyleSheet, Platform, Dimensions } from 'react-native';
import { colors, typography, spacing, shadows } from './GlobalStyles';

const { width, height } = Dimensions.get('window');

export const QuestionsStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background,
    },
    header: {
        paddingTop: Platform.OS === 'ios' ? 60 : 20,
        paddingBottom: spacing.md,
        paddingHorizontal: spacing.md,
        backgroundColor: colors.surface,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderBottomWidth: 1,
        borderBottomColor: colors.border.light,
        ...shadows.small,
    },
    title: {
        ...typography.h2,
        color: colors.text.primary,
    },
    clearButton: {
        padding: spacing.sm,
        borderRadius: 20,
        backgroundColor: colors.surfaceSecondary,
        ...shadows.small,
    },
    messagesContainer: {
        flex: 1,
        paddingHorizontal: spacing.md,
        backgroundColor: colors.background,
    },
    messagesContentContainer: {
        paddingVertical: spacing.md,
        flexGrow: 1,
        paddingBottom: spacing.lg,
    },
    messageBubble: {
        maxWidth: width * 0.75,
        padding: spacing.md,
        borderRadius: 20,
        marginBottom: spacing.sm,
        minWidth: 60,
        ...shadows.small,
    },
    userMessage: {
        alignSelf: 'flex-end',
        backgroundColor: colors.primary,
        borderBottomRightRadius: 6,
    },
    botMessage: {
        alignSelf: 'flex-start',
        backgroundColor: colors.surface,
        borderBottomLeftRadius: 6,
        borderWidth: 1,
        borderColor: colors.border.light,
    },
    userMessageText: {
        ...typography.body1,
        color: colors.text.inverse,
    },
    botMessageText: {
        ...typography.body1,
        color: colors.text.primary,
    },
    userMessageTimestamp: {
        ...typography.caption,
        color: 'rgba(255, 255, 255, 0.7)',
        marginTop: spacing.xs,
        alignSelf: 'flex-end',
    },
    botMessageTimestamp: {
        ...typography.caption,
        color: colors.text.tertiary,
        marginTop: spacing.xs,
        alignSelf: 'flex-start',
    },
    loadingBubble: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderWidth: 1,
        borderColor: colors.border.light,
        borderBottomLeftRadius: 6,
        padding: spacing.md,
        borderRadius: 20,
        ...shadows.small,
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.md,
        borderTopWidth: 1,
        borderTopColor: colors.border.light,
        backgroundColor: colors.surface,
        ...shadows.medium,
        minHeight: 72,
    },
    input: {
        flex: 1,
        backgroundColor: colors.surfaceSecondary,
        borderRadius: 24,
        paddingHorizontal: spacing.md,
        paddingVertical: Platform.OS === 'ios' ? 12 : 10,
        ...typography.body1,
        maxHeight: 120,
        minHeight: 48,
        borderWidth: 1,
        borderColor: colors.border.light,
        color: colors.text.primary,
        marginRight: spacing.sm,
    },
    inputActive: {
        borderColor: colors.primary,
        backgroundColor: colors.surface,
    },
    sendButton: {
        padding: spacing.md,
        borderRadius: 24,
        backgroundColor: colors.primary,
        ...shadows.medium,
        minWidth: 48,
        minHeight: 48,
        justifyContent: 'center',
        alignItems: 'center',
    },
    sendButtonText: {
        ...typography.button,
        color: colors.text.inverse,
    },
    sendButtonDisabled: {
        backgroundColor: colors.border.medium,
        shadowOpacity: 0,
        elevation: 0,
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        minHeight: height * 0.5,
        paddingHorizontal: spacing.xl,
    },
    emptyIcon: {
        marginBottom: spacing.lg,
        opacity: 0.6,
    },
    emptyText: {
        ...typography.h3,
        color: colors.text.primary,
        marginBottom: spacing.sm,
        textAlign: 'center',
    },
    emptySubtext: {
        ...typography.body1,
        color: colors.text.secondary,
        textAlign: 'center',
        lineHeight: 24,
    },
    suggestionContainer: {
        marginTop: spacing.xl,
        width: '100%',
    },
    suggestionTitle: {
        ...typography.body1,
        fontWeight: '600' as const,
        color: colors.text.primary,
        marginBottom: spacing.sm,
        textAlign: 'center',
    },
    suggestionChips: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'center',
        gap: spacing.sm,
    },
    suggestionChip: {
        backgroundColor: colors.surface,
        borderWidth: 1,
        borderColor: colors.border.light,
        borderRadius: 20,
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.sm,
        marginHorizontal: 2,
        marginVertical: 2,
        ...shadows.small,
    },
    suggestionChipText: {
        ...typography.body2,
        color: colors.primary,
        fontWeight: '500' as const,
    },
    confirmOverlay: {
        position: 'absolute',
        left: 0,
        top: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.3)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 100,
    },
    confirmModal: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 24,
        width: 280,
        alignItems: 'center',
    },
    confirmTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1A1A1A',
        marginBottom: 20,
        textAlign: 'center',
    },
    confirmActions: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
    },
    confirmCancel: {
        flex: 1,
        padding: 12,
        borderRadius: 8,
        backgroundColor: '#F2F2F7',
        marginRight: 8,
        alignItems: 'center',
    },
    confirmCancelText: {
        color: '#8E8E93',
        fontWeight: '600',
    },
    confirmDelete: {
        flex: 1,
        padding: 12,
        borderRadius: 8,
        backgroundColor: '#FF6B35',
        alignItems: 'center',
    },
    confirmDeleteText: {
        color: '#fff',
        fontWeight: '600',
    },
});
